// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMvrhRLIkZWQvzGztlA8S3hCJ0-FIty4Q',
    appId: '1:260863360671:web:52e9b81064bc019f69ecaa',
    messagingSenderId: '260863360671',
    projectId: 'aladdinslamp-befc1',
    authDomain: 'aladdinslamp-befc1.firebaseapp.com',
    storageBucket: 'aladdinslamp-befc1.firebasestorage.app',
    measurementId: 'G-LE3GPBVXE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl8uPncQhgAuycG1CumAdRZHgBjNB7VYc',
    appId: '1:260863360671:android:b1a11e2eb4778dc869ecaa',
    messagingSenderId: '260863360671',
    projectId: 'aladdinslamp-befc1',
    storageBucket: 'aladdinslamp-befc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsmthgDJT4rmaqqx4jhVG-teFJv4g9rew',
    appId: '1:260863360671:ios:53a798bbaff612a369ecaa',
    messagingSenderId: '260863360671',
    projectId: 'aladdinslamp-befc1',
    storageBucket: 'aladdinslamp-befc1.firebasestorage.app',
    androidClientId: '260863360671-ne58e7geejni7e64nqbn3arbk3qk0irh.apps.googleusercontent.com',
    iosClientId: '260863360671-isb9aahfmucerh4jlq0af8et4mqcpqhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.aladdinslamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMvrhRLIkZWQvzGztlA8S3hCJ0-FIty4Q',
    appId: '1:260863360671:web:7f841e4e531d8bb869ecaa',
    messagingSenderId: '260863360671',
    projectId: 'aladdinslamp-befc1',
    authDomain: 'aladdinslamp-befc1.firebaseapp.com',
    storageBucket: 'aladdinslamp-befc1.firebasestorage.app',
    measurementId: 'G-CCM6H942WQ',
  );

}